# fly.toml app configuration file generated for back-the-miles on 2023-08-13T19:13:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "back-the-miles"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  AUTH0_AUDIENCE = "https://backthemiles.com"
  AUTH0_DOMAIN = "leapfrog.eu.auth0.com"
  CLIENT_ORIGIN_URL = "https://capture-the-miles.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

app = "back-the-miles"
primary_region = "ams"
